language: python
# ===== Linux ======
dist: xenial
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
install: "pip install -r requirements/requirements.txt "
script: python -m unittest discover

matrix:
  include:
    - name: "Python 3.7.5 on macOS 10.14"
      os: osx
      osx_image: xcode10.2  # Python 3.7.5 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - sudo chown -R travis:travis $TRAVIS_BUILD_DIR
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
        - pip3 install codecov
      script: python3 -m pytest
      after_success: python 3 -m codecov

    - name: "Python 3.8.0 on macOS 10.14"
      os: osx
      osx_image: xcode11.3  # Python 3.8.0 running on macOS 10.14.6
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - sudo chown -R travis:travis $TRAVIS_BUILD_DIR
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
        - pip3 install codecov
      script: python3 -m pytest
      after_success: python 3 -m codecov


      #  ====== WINDOWS =========
    - name: "Python 2.7 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell # 'language: python' errors Travis CI Windows
      before_install:
        - sudo chown -R travis:travis $TRAVIS_BUILD_DIR
        - choco install python2
        - python --version
        - python -m pip install --upgrade pip
        - pip install --upgrade pytest
        - pip install codecov
      env: PATH=/c/Python27:/c/Python27/Scripts:$PATH

    - name: "Python 3.5.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - sudo chown -R travis:travis $TRAVIS_BUILD_DIR
        - choco install python --version 3.5.4
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install codecov
      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH

    - name: "Python 3.6.8 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - sudo chown -R travis:travis $TRAVIS_BUILD_DIR
        - choco install python --version 3.6.8
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install codecov
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH